version: '3'
services:
  backend:
    hostname: backend
    image: damoklov/backend
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - API_KEY=$API_KEY
      - AWS_REGION=us-east-1
      - STORAGE_GAMESTOREDB_NAME=gamestore-iot
    build:
      dockerfile: ./backend/Dockerfile
    deploy:
      x-aws-autoscaling: 
        cpu: 10
        max: 2
    ports:
      - 5000:5000
  frontend:
    hostname: frontend
    depends_on: 
      - backend
    image: damoklov/frontend
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80


